#cloud-config

apt:
  sources:
    docker:
      keyid: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
      source: 'deb [arch="amd64" signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu jammy stable'

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
package_update: true
package_upgrade: true
package_reboot_if_required: true

write_files:
  - content: |
      {
      "userland-proxy": false,
      "ipv6": true,
      "fixed-cidr-v6": "fd00:111::/64"
      "experimental": true,
      "ip6tables": true
      }
