name: apply

on:
  push:
    branches:
      - main

permissions: read-all

env:
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
  HETZNER_DNS_API_TOKEN: ${{ secrets.HETZNER_DNS_API_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup SSH-Key(s)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_ED25519_INFRA }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: |
          terraform init
      - name: Terraform apply
        run: |
          terraform apply -auto-approve -input=false
