name: plan

on:
  pull_request:
    branches:
      - main

permissions: read-all

env:
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
  HETZNER_DNS_API_TOKEN: ${{ secrets.HETZNER_DNS_API_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: |
          terraform init
      - name: Check format
        run: |
          terraform fmt -check
      - name: Plan
        run: |
          terraform plan
